### ISSUE TITLE
SecurityManager: DirectorySecurityManager issues

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1021]
chmod -R 755 does not work as expected (v6r4p28)
The content of a directory does not have the rights updated

**Comment by marianne013** [comment]
According to our cfg we do. I think the reasoning is that we don't want users of different VOs meddle with the files of another VO.

**Comment by chaen** [comment]
It clearly makes sense :-) The security manager are somewhat very poor in their logic, but if it's sufficient for your needs, perfect ! Do you know if any of the issue above is still true ?

**Comment by andresailer** [comment]
We are using the "FullSecurityManager"

**Comment by marianne013** [comment]
I just did a quick test:
chmod -R 755 seems to set the permissions as expected, i.e. all the files and subdirs change.
chown -R also seems to work, according to the catalogue Simon now owns all my junk files :-D
But: When I actually go and remove the read permission from the directory owned by Simon I can still read the directory as me.
Probably because of this:
 ```
if self.db.globalReadAccess:
      for path in permissions:
permissions[path]['Read'] = True
```
Though this suits us. No secret files. I cannot write to the directory owned by Simon, which is what we wanted to enforce, so usually I would close this as "Works for me"

**Comment by chaen** [comment]
I suspect you can remove though, no ?

**Comment by marianne013** [comment]
I can't remove anything from Simon's dir and and I can't chown it back, so this looks all safe to me.

**Comment by chaen** [comment]
Ah no, I remember now the issue I had with this: removing a non existing directory is not allowed. That's why there is the `DirectorySecurityManagerWithDelete`. OK so if it all works as expected, shall we close ?

**Comment by chaen** [comment]
I guess yes
