### ISSUE TITLE
v6r8p11: dirac-pilot flavor wrong

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1483]
The following block
```python
if os.environ.has_key( 'EDG_WL_JOBID' ):
  cliParams.flavour = 'LCG'
  pilotRef = os.environ['EDG_WL_JOBID']

if os.environ.has_key( 'GLITE_WMS_JOBID' ):
  if os.environ['GLITE_WMS_JOBID'] != 'N/A':
    cliParams.flavour = 'gLite'
    pilotRef = os.environ['GLITE_WMS_JOBID']
    
if os.environ.has_key( 'OSG_WN_TMP' ):
  cliParams.flavour = 'OSG'    
```
should use ```elif``` I think. Otherwise GLITE WNs can become OSG...

**Comment by fstagni** [comment]
Does this really make sense? Anyway we do direct submission to the CEs, we know at submission time CEName and QueueName, so does it really make sense to know? We can know the flavour already at server side. 

On a related note, the PilotReference inside the pilot is used up to now so that the Matcher reports that a matched pilot goes in status "Running". This should be a job done by the pilot itself (so independently from where it runs) so this variable can disappear. The other point where this is used is in the StalledJobAgent, to get the status of a pilot. I would say this is not strictly needed, at least not the way it is done.

**Comment by fstagni** [comment]
Closed as invalid. Also regarding the "PilotReference": it will be changed with the pilot logging system.
