### ISSUE TITLE
DIRAC modules with same name as system modules

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#2207]
Would it be possible to get rid of the Dirac modules that "replace" the system modules just with a difference in the fact that names are capitalized... 
It is a real pain, for example when the disk on which Dirac is is mounted with case-insensitive namespace... 
Very likely most of them should just be removed and replaced by the python native ones (e.g. Time that mainly replaces datetime.py and not time.py)
More generally a review of the obsolete or almost useless modules that may have had an interest with python 2.1 should be made and replaced by the current python native implementation...

**Comment by fstagni** [comment]
Discussed briefly at today's BiLD meeting (!!).

- see if they be be ditched
- add deprecation warnings to the old names
- change names

**Comment by chrisburr** [comment]
From v7r2 the names should be less of a problem as `from __future__ import absolute_imports` is used everywhere to get Python 3 style imports. This then means you need to use `from . import Time` instead of `import Time`.

That said, the majority of this code can probably be dropped in v7r3 (after adding deprecation notices to v7r2).

**Comment by phicharp** [comment]
Hmmmm... happy to see that this 6 years old issue is being tackled! ;-)
