### ISSUE TITLE
Indicate of certificate expiration problem

### ISSUE THREAD

**Issue by sashabaranov** [DIRACGrid/DIRAC#2955]
As discussed with @zmathe:

Currently if you use BookkeepingClient and parseCommandLine with expired certificate you have no sane way to handle this other then parsing log for `ERROR` presence, DIRAC library just does `sys.exit(0)` and writes to log.

I can see two solutions:
1. BookkeepingClient should have a way of indicating that connection error occured and throw an exception, which can be handled in code that uses it.
2. `sys.exit(1)` or something should be called in that situation

PS Having DIRAC to parse my command line arguments seems odd to me, there are [good libraries](http://click.pocoo.org/5/) for that. I would love isolate DIRAC from my scripts. A way to initialise BookkeepingClient with my own dirac.cfg, use it the way I want without any cli argument parsing involved.

**Comment by atsareg** [comment]
I am not sure I understand the whole issue of the BookkeepingClient and parseCommandLine with expired certificate, but concerning the PS:
you can use your own arguments to your commands that you can parse yourself. DIRAC will parse only its specific switches ( -o, -s, -c, -d, -h ). If you do not use those, there should not be a conflict with the DIRAC parsing your input.

**Comment by zmathe** [comment]
The problem is they want to use a host certificate instead of a proxy to contact the bkk using DIRAC on CVMFS.  As this is not an official way to do, they have to use the parseCommandLine and a dirac.cfg. But if some problem occurs for example: the proxy expire, the parseCommandLine exit. The first proposed solution make no sense to me, becuase the retVal['OK'] fasle is case of error:
```python
retVal =  bk.setRunAndProcessingPassDataQuality(int(sys.argv[-2]), path, flag)
```
 The second solution is not clear to me.
