### ISSUE TITLE
[v6r14] MatchingDelay option doesn't introduce any delay

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/DIRAC#2983]
The 'MatchingDelay' option does not work in the sense that no delay is introuduced in the matching. Here below how I've spotted out the problem:
1. In the Operation section of the CS, I've set:

  JobScheduling
    {
      CheckMatchingDelay = True
      EnableSharesCorrection = True
      MatchingDelay
      {
        LCG.IN2P3-CC.fr
        {
          JobType
          {
            CorsikaRepro = 120
          }
1. I submit 3 jobs just one after the other with a specific type:

job.setType('CorsikaRepro')
1. In the logging info of the jobs, I found that they are have been matched at the same time:

15h20
15h20
15h20

so without any delay. I've also checked the logs of the Matcher and I've seen no indications of a delay, even if I found:

`WorkloadManagement_Matcher/log/#current#:2016-01-08 15:05:37 UTC WorkloadManagement/Matcher   INFO: Negative conditions for site LCG.IN2P3-CC.fr are: {'JobType': ['CorsikaRepro']}`

**Comment by andresailer** [comment]
Is this because every time `requestJob` is called a new `Matcher` object is created?

https://github.com/DIRACGrid/DIRAC/blob/08670cda77d61d7d1ff3208679ded9d252d7e6ce/WorkloadManagementSystem/Service/MatcherHandler.py#L89

That `Matcher` object contains a `Limiter` object, which stores the latest matched job, and then goes out of scope.

Probably these member variables should be turned back into class static variables
https://github.com/DIRACGrid/DIRAC/blob/08670cda77d61d7d1ff3208679ded9d252d7e6ce/WorkloadManagementSystem/Client/Limiter.py#L23-L25

**Comment by andresailer** [comment]
I am going to claim this is solved in v7r0p11
