### ISSUE TITLE
New URL for global defaults CFG files

### ISSUE THREAD

**Issue by closier** [DIRACGrid/DIRAC#3478]
In order to prepare the phaseout of AFS at CERN where global defaults CFG files are stored with the tars for DIRAC, External and lcgBundles we need to modify the PATH which is hard coded in : 
- Core/scripts/dirac-distribution.py
- Core/scripts/dirac-install-client.py
- Core/scripts/dirac-install.py
- WorkloadManagementSyetm/Agent/DiracSiteAgent.py
- WorkloadManagementSyetm/PilotAgent/dirac-pilot.py

http://lhcbproject.web.cern.ch/lhcbproject/dist/DIRAC3 should be replace by http://cern.ch/diracproject

**Comment by fstagni** [comment]
I guess this is not only for the new global defaults CFG files, but also for the tars location.

Code-wise this is easy, because for e.g. dirac-install it is as simple as doing something like:
```
try:
  urllib2.urlopen("a url")
except HTTPError:
  urllib2.urlopen("the other url")
```

For dirac-distribution, which instead uploads the tarballs, and creates the "tars.list" file, we need to modify it such that it adds tarballs (and the file above) in both locations, OR to the EOS location only, once it's available, as right now we upload to AFS and we serve from the AFS webserver.

**Comment by closier** [comment]
THE new location is there and can be use already. I did some local tests and i manage to install dirac from the new location. So I was thinking to keep in sync both repo during the transition period.

**Comment by chaen** [comment]
This should be the opportunity to add a features which should be there for a long time IMHO: make these urls customizable ! Because they are hardcoded, it is just impossible to "install the head". So we should make it changeable: either by a configuration file, or flags in dirac-install.

**Comment by chaen** [comment]
This is part of https://github.com/DIRACGrid/DIRAC/issues/3517

**Comment by fstagni** [comment]
So, let's close this one. I will add a x-ref in #3517.
