### ISSUE TITLE
Choose singularity from site level

### ISSUE THREAD

**Issue by zhangxiaomei** [DIRACGrid/DIRAC#3674]
Not all the sites are ready to or want to provide singularity at the same period. Here is the way which the site can choose to use singularity or not:
(1) CS ( Supposed CEType is set to be "Singularity" for JobAgent )
/Resources/Sites/Container = False ( True is default )
(2) Define CEType in local config through pilotCommands.py? or siteDirector.py?
/LocalSite/LocalCE = InProcess
(3) JobAgent then decide which CEType to use
In this way, sites can be free to choose singularity or not

**Comment by fstagni** [comment]
Are these cases covered in https://github.com/DIRACGrid/DIRAC/issues/3381 ?

**Comment by zhangxiaomei** [comment]
I think yes.  But I didn't see the implementation details.  If not available, I would like to procced it to make it available. I am not sure which is the right place to set "/LocalSite/LocalCE"

**Comment by fstagni** [comment]
@sfayer can you comment?

In general, these changes would need to be done at least in Pilot3, and maybe also in pilot2. I am always in favor of pilots self-discovering their own environment, as this is much more generic (not all pilots are started by a SiteDirector) so to me this is something that should be fit in one of the pilot commands.

**Comment by sfayer** [comment]
For point 1, yes I think the DIRAC admin should be able to control whether containers are enabled on a site-by-site or CE-by-CE basis in the Configuration system. It may be better to default to off for now just until things are more widely tested.

For 2 and 3: Yes, I think there should be a pilotCommands function for detecting WN container support (ideally it should be written considering we may have more than just singularity, i.e. docker, in the future). I think the logic should be:
- If the SINGULARITY_BIN variable is set, use that for the singularity executable.
- If SINGULARITY_BIN is set to "none", explicitly disable singularity support.
- Otherwise check $PATH for the singularity executable, if it isn't found, default to "none".

(I've invented the SINGULARITY_BIN environment variable: It may be worth checking if other communities already have something like this).

That should allow for auto-detection and allow sites to easily opt-out for any reason.

The above should probably set a separate option in the local configuration /LocalSite/Containers with the result of the test. Completely overriding the LocalCE option may be a bit drastic: Perhaps we can add an "autodetection" CE module that just runs SingularityCE or InProcess depending on the value of /LocalSite/Containers (and the central CS options)? It would then just be a case of setting something like /LocalSite/LocalCE=autodetect as the CE in the pilot options to get the desired behaviour.

Does that make sense? It's been a while since I last looked at this stuff, so it may be I've forgotten how it all fits together...

Regards,
Simon

**Comment by fstagni** [comment]
What if /LocalSite/LocalCE is a list of CEs in order of preference?
I am not too much in favor of more CS sections unless they are really necessary.

**Comment by zhangxiaomei** [comment]
Not clear about two points:
(1)  The SINGULARITY_BIN variable is an env parameters which need sites to set? Does it get the path of singularity executable from CS too?
 (2) Autodetection is really needed？
 In some cases, the existing executable doesn't mean the sites are completely ready for singularity. Also autodection is possible to make the sites who has problems with singularity are not easy to find the problems since autodetection just silently changed to Inprocess.

**Comment by sfayer** [comment]
@fstagni: Yes, I think a list in LocalCE would work well... That way the "is singularity installed here" code can be fully contained within the SingularityCE module itself, no need to modify the pilotCommands.

@zhangxiaomei:
1) Using the SINGULARITY_BIN is just a suggestion... Most sites wouldn't need to set it (the binary would be found on PATH instead), it would just be for sites that have installed it in an unusual location or if they want to stop DIRAC from using singularity even though its installed (mainly for the case where jobs are submitted via a SiteDirector, so the site admin can't just change the LocalCE list). I don't think the singularity path should go into the CS at all.
2) I think some form of autodetection is needed so that if singularity is enabled on DIRAC but the pilot finds itself on a WN without singularity it can move onto the next item in the LocalCE list. If singularity is *required* then setting LocalCE to just SingularityCE would effectively disable the fallback.

**Comment by zhangxiaomei** [comment]
As I understand, when container = true in CS, we set /LocalSite/LocalCE to be a list. eg. Singularity, Inprocess in PilotCommands. Then JobAgent try with SingularityCE. If not Singularity is available, InprocessCE will be chosen at the end. Is that right?

**Comment by zhangxiaomei** [comment]
As I understand, when container = true in CS, we set /LocalSite/LocalCE to be a list. eg. Singularity, Inprocess in PilotCommands. Then JobAgent try first with SingularityCE. If no Singularity is available in WN, InprocessCE will be chosen at the end. If Singualrity is required, we just set LocalCE to be Singualrity, not a list.  Is that right?
Do we need another flag in CS for users to choose if singularity or container is required? or we can do like this:
     If CEType = "Singularity"  for  JobAgent in CS
          Singularity is required
         If Container = false 
           not use singularity
     If CEType = "InProcess" for JobAgent in CS
         If Container = true for sites
            fallback can happen

In fact. in our case, we don't like fallback, which possibly mean the application could run in a wrong OS and the physics result could not be accepted is some case.

**Comment by sfayer** [comment]
I'm not sure that LocalCE can be a list at the moment... That's probably a feature that would need implementing; perhaps @fstagni can comment?

Yes, if Singularity is required, just set that as the LocalCE, I think that should work with the code as-is. If you don't want fallback, then maybe don't worry about that too much (although I thought that was the point of the ticket... Not all sites would have singularity immediately, so they could decide not to use it yet?).

If some minimal level of fallback is required (which we can build on in the future), then my suggestion would be: Each site has a containers No/Yes/Required flag and LocalCE is set to "SingularityCE,InProcess". The algorithm would be something like, in JobAgent:
```
For each CE in LocalCE list:
  Check if CE supported on node:
    Yes => Use this CE
    No => Continue
    Error => Break
```
And then in SingularityCE "Check if supported function":
```
SingularityOK = Check if Singularity binary is installed.
Check Site Containers CS setting:
  No => Return
  Yes => Return SingularityOK
  Required => If Singularity OK return Yes, otherwise return Error.
```
In your case you can just set it to Required for sites which have singularity ready and leave it as the default No elsewhere: Which I think is what you want?

I think in the long-run we'll need to do something with platforms: Specifically gather the all the platforms that singularity can provide on the node + the base platform and then match the jobs on that (that way a user/job can request a specific platform rather than caring about the infrastructure). I think we're quite a way off from that all fitting together yet.

**Comment by fstagni** [comment]
I believe that v7r1 (together with DIRACOS that includes Singularity) covers all the requests above. I close this task, feel free to comment or re-open it in case I am wrong.
