### ISSUE TITLE
Multi-VO Transformation System

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3695]
The WorkflowTaskAgent and RequestTask agent currently use a shifterProxy, which is then (only?) used to set the owner credentials of the new Jobs or Requests. 

https://github.com/DIRACGrid/DIRAC/blob/eb0286feaea85e6112bbe8de6c4f01a378b5ec89/TransformationSystem/Agent/TaskManagerAgentBase.py#L176-L184

There are no contacts to things outside of DIRAC, so the host credentials should be enough for the agent to run, right?

Then there two options:

1) get rid of the shifterProxy and use the user/group of the person that created the transformation, which are part of the transformation object to create the jobs/requests
2) use the group of the transformation creator and get the VO and then the VO dependent shifter(proxy) to use those credentials (name/group) to create the new jobs/requests.

In either case the global owner/group member variables need to be moved to the individual transformations to allow one agent to treat multiple VOs, which needs some changes all over the place.

**Comment by chaen** [comment]
Just to say: I have no clue if that's the case or not, but if the systems use the DFC in write mode, they need a proxy.

**Comment by andresailer** [comment]
Of the top of my head I cannot think of anything in these agents that would need to write to the DFC, but it is good to keep in mind.

**Comment by fstagni** [comment]
The reason why the `shifterProxy` can be used is to set a different owner group for each transformation type, that could later be used to set different priorities (via the JobShare group parameter).

For example, in LHCb we have a WorkflowTaskAgent that only runs on "MCSimulation", a second on "RealData", a third on "everything else", and they all have a different shifterProxy in their cfg in order to adjust the jobs' priorities. The user/group that is used for lunching the production is not necessarily the one that you want to use for running the jobs.

So, your option 1 is not viable, but what CAN be done is to use the return code from `getProxyInfo`, when it can't find the proxy, and only in this case use the user/group of the person that created the transformation. 

You may still need to satisfy the case when multiple WorkflowTaskAgents may need to be run. E.g. you should run one of these agents per VO, and for simplicity the VO should be a parameter of the Transformations table.

**Comment by andresailer** [comment]
OK, the possibility to define the shifter credentials to be used will stay. Would it be acceptable if the name changes, because the `shifterProxy` has the side effect of creating a proxy, which might not be necessary?

Which would mean in the end:
If there are shifter proxy/credentials set, use those to submit the jobs/requests, if not use the credentials (name, group) of the person that submitted the transformation, no additional look up of VO shifters.

Further reasoning:

I don't like adding a parameter to the Transformations table because that is a big pain to do for existing transformations and might come back to haunt someone eventually. However, each group is connected to no more than a single VO, right? So we can always use the group to get the VO.

I think we want to make it possible for one WTA to run over the transformations of multiple VOs, right?
Then the selection should stay with the TransformationTypes _only_, otherwise one might quickly run into the problem that some transformations are treated by multiple agents.

Thus, if one wants to separate their WTA by VO they should use different TransformationTypes (e.g., MCSimulation_VO) and pick only those for the WTA.

**Comment by fstagni** [comment]
My idea was to have the possibility to instantiate an agent treating only certain VO(s), but keeping also the possibility to work on certain TransformationTypes. I am anyway fine with everything. 

Do you have a real life use case on multiple VOs wanting to run some transformations? For testing purposes.

**Comment by andresailer** [comment]
I think it is just easier to have the option to run one agent for multiple VOs, if then one VO starts to grow it can evolve into its own agent. It would also be possible to add a VO option, but that would need to be mandatory or there might be the case where multiple agents treat the same transformations.

I.e.:
AgentA : treat MCGeneration, MCSimulation
AgentB: treat MCGeneration, MCSimulation but only VO=foo
oops, forgot to set AgentA only to VO=bar, now it runs foo and bar

@marianne013 @sfayer @hamar @atsareg you have many more VOs than me or Federico, what do you think?

**Comment by sfayer** [comment]
For the "lots of small VOs" case, I think the fewer agents required to be installed (i.e. if VOs can share an agent) the better... It's quite common for a VO to want to try things out and the less work we have to do centrally to allow that the better (even if they can only get the most basic set of plugins/transformation types that way). Not to mention fewer things for us to monitor & test...

The ideal case would be if we can run a single set of basic transformation agents/services for all of our VOs. That way the enthusiastic users can play around with it without having to ask us to enable things specially (which in the past has worked as a great way to encourage communities to use more features on DIRAC).

**Comment by andresailer** [comment]
I progressed a bit, but one needs a proxy to submit, at least to upload the input sandbox to the SandboxStore.
Is there anyway to do this with the server credentials instead?

**Comment by andresailer** [comment]
It seems to be possible to pass the useCertificates=True, and delegatedDN and delegatedGroup to the clients to enable submission and owner of production basis, but that would basically prevent re-use of clients and a bit more reworking of things.

**Comment by andresailer** [comment]
As far as I understand, the changing of the execution proxy is a total killer of performance.

**Comment by atsareg** [comment]
Why ? Especially with bulk submission, this should not be a problem.

**Comment by atsareg** [comment]
I guess, you mean that the transformation agents are multi-threaded and the operations should be executed with a lock to prevent spoiling thread environments. If this has a serious performance penalty, then the solutions can be:
1. Use ProcessPool instead of ThreadPool inside the agents
2. Perform all the operations with credentials delegation and with the host certificate. The host must be trusted in this case
3. Enhance WMS and RMS interfaces to allow submission with the credentials different from the ownership of the resulting jobs and requests. Then the submission can be done with a "global shifter" proxy or with the host certificate with appropriate properties.

The case 1. is the simplest but someone can be anxious about its reliability. This is how REA is working. In this case it can be simpler, since we can have a fixed number of processes created at the beginning and not changing them dynamically.

The case 2. and 3. might not work if third party services should be called on the owner behalf, so it is not universal

**Comment by andresailer** [comment]
So I have implemented point 2. of @atsareg 's comment. This will work for the DIRAC transformation system out of the box, and makes life for administrators of many small VOs the easiest. If a VO develops additions to their transformation workflow that requires access to external resources they can still run their dedicated agents with a shifterProxy.

**Comment by fstagni** [comment]
Can this task be closed? The above PR is in v6r20p5

**Comment by andresailer** [comment]
At least the TransformationCleaningAgent still needs to be made MultiVO capable.

**Comment by andresailer** [comment]
All merged for v6r20p7
