### ISSUE TITLE
TransformationDB DataFiles table is never cleaned

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3710]
It seems to me that the DataFiles table in TransformationDB is never cleaned of LFNs that no longer belong to any Transformation. I don't see any code in the TransformationDB.py

Is that on purpose or an oversight?

PS: For those that have been using the Transformation system prior to v6r10, you might be missing and index in the DataFiles table, which was introduced here https://github.com/DIRACGrid/DIRAC/commit/e80259796401c47037b85edcad7b05776eae93eb but was not part of the PR mentioned here https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-v6r10

**Comment by fstagni** [comment]
I think it has been an oversight, but I remember we talked about this in the past and right now I can't recall the conclusion, maybe @arrabito remember?

Also in https://github.com/DIRACGrid/DIRAC/issues/1091 we talked about removing entries from this table.

**Comment by arrabito** [comment]
I don't really remember if there was any good reason for keeping them.

**Comment by chaen** [comment]
FYI, I cleaned our table yesterday using the following queries (careful, long query !)
```
delete d from DataFiles d LEFT OUTER JOIN TransformationFiles t on d.FileID = t.FileID where t.FileID is NULL;
```

About the index, it is not a good idea because due to the parallelism of the TransformationAgent, you can end up with duplicated entries for a given LFN, which results in the LFN being processed multiple times.

@phicharp made a PR in which he replaces the INDEX with a UNIQUE constraint, but you still to do it operationally. The steps go as follow:

1) Remove the duplicated entries
2) Drop the index
3) Remove useless entries
4) Add the unique constraint
5) Pay a beer to Chris

In details:
Of course, the best is if you can stop completely all the TS components befoer starting. 
Jobs that need to update the entries in the TS will go to completed and create a SetFileStatus Request for the RMS, so you wont lose anything. 

1) Removing the duplicated entries

You can find them with this query
```
 select LFN, count(*) as t from DataFiles group by LFN having t > 1;
```

But then you have to handle operationally what yo do with these files. One of the entry has to disappear. Beware that they are referenced in the TransformationFiles table, and that you might have TransformationTasks and TransformationFileTasks pointing to them. So the action to take depends on your cases, but all in all, there should be one and only one left at the end. 

2) Easy

```
Drop index `LFN` on DataFiles
```

FYI, you drop the index before removing the data so that it is not rebuilt all the time

3) See query at the very top of this post

4) ALTER TABLE DataFiles ADD UNIQUE (LFN);

5) I'm sure you have the know-how for that

**Comment by andresailer** [comment]
If we write this query like this:
```
DELETE d FROM DataFiles AS d JOIN (SELECT da.FileID FROM DataFiles AS da LEFT JOIN TransformationFiles AS tf on da.FileID = tf.FileID WHERE tf.FileID is NULL LIMIT 1000) d2 ON d2.FileID = d.FileID
```
We can use a limit and slowly eat away at the superfluous entries in the DataFiles table.
Except that we cannot prevent entries that belong to currently added files from being removed :(
