### ISSUE TITLE
[v6r20] SI00 information and the SiteDirector

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3790]
The sitedirector needs a value for SI00 either in the CE or Queue options, 
https://github.com/DIRACGrid/DIRAC/blob/ef1a0b435f294143c3eae7767238b98c50e6fe6e/WorkloadManagementSystem/Agent/SiteDirector.py#L301-L309

otherwise the queue is ignored and no pilots are submitted

https://github.com/DIRACGrid/DIRAC/blob/ef1a0b435f294143c3eae7767238b98c50e6fe6e/WorkloadManagementSystem/Agent/SiteDirector.py#L477-L481

As there is no such information for the CERN CEs (and for other CEs it is a mess in Glue2), I just added some dummy values by hand.
If this information is mandatory to know for proper functioning we need to lobby the information provides to provide this information in a sensible way. If it not necessary we should drop reliance on its existence.

**Comment by fstagni** [comment]
SI00 (SpecInt 2000) is the old benchmark, the "new" one is HS06 (HepSpec 2006) (and apparently we'll stay with that for long time, as the newer versions of benchmark suites don't give any better precision... but this is a different story).

The fact that in the CS there's still "SI00" instead of a "HS06" is because of... historical reasons mainly. Also, many WLCG sites refused for very long time to publish HS06 and kept publishing SI00, which of course added to the confusion.

DIRAC uses HS06, and the fast benchmark "DB12" which is run inside the pilot is an approximation of HS06 (and sometimes it happens to be closer to "reality" than HS06... but again this is another story).
There is a simple conversion between SI00 and HS06 which is in this line:

https://github.com/DIRACGrid/DIRAC/blob/ef1a0b435f294143c3eae7767238b98c50e6fe6e/WorkloadManagementSystem/Agent/SiteDirector.py#L308

To add to the confusion the SI00 is/was published in minutes (!!!) while HS06 "correctly" uses seconds, so this explains the "*60" in the line above.

First question is: do the Glue2 schema at CERN publish HS06?

Anyway, as said, the DIRAC pilot calculates the benchmark on the fly with the fast DB12. And more and more the direction that we take is to "let the pilot do the logic", plus this value may not be too close to reality, so to cut story short I would drop completely this check, and consequently the need for setting a confusing SI00 in CS.

**Comment by andresailer** [comment]
The only benchmarks published by cern are for ceatlastzero[12]
```
$ ldapsearch -x -LLL -o ldif-wrap=no -h lcg-bdii.cern.ch:2170 -b o=glue "(&(objectClass=*))" | grep -i Benchmark | grep -i cern
dn: GLUE2BenchmarkID=ceatlastzero1.cern.ch_HEP-SPEC06,GLUE2ResourceID=ceatlastzero1.cern.ch,GLUE2ServiceID=ceatlastzero1.cern.ch_ComputingElement,GLUE2GroupID=resource,GLUE2DomainID=CERN-PROD,GLUE2GroupID=grid,o=glue
GLUE2BenchmarkExecutionEnvironmentForeignKey: ceatlastzero1.cern.ch
GLUE2BenchmarkID: ceatlastzero1.cern.ch_HEP-SPEC06
GLUE2BenchmarkComputingManagerForeignKey: ceatlastzero1.cern.ch_ComputingElement_Manager
dn: GLUE2BenchmarkID=ceatlastzero2.cern.ch_HEP-SPEC06,GLUE2ResourceID=ceatlastzero2.cern.ch,GLUE2ServiceID=ceatlastzero2.cern.ch_ComputingElement,GLUE2GroupID=resource,GLUE2DomainID=CERN-PROD,GLUE2GroupID=grid,o=glue
GLUE2BenchmarkExecutionEnvironmentForeignKey: ceatlastzero2.cern.ch
GLUE2BenchmarkID: ceatlastzero2.cern.ch_HEP-SPEC06
GLUE2BenchmarkComputingManagerForeignKey: ceatlastzero2.cern.ch_ComputingElement_Manager
dn: GLUE2BenchmarkID=ceatlastzero2.cern.ch_specint2000,GLUE2ResourceID=ceatlastzero2.cern.ch,GLUE2ServiceID=ceatlastzero2.cern.ch_ComputingElement,GLUE2GroupID=resource,GLUE2DomainID=CERN-PROD,GLUE2GroupID=grid,o=glue
GLUE2BenchmarkExecutionEnvironmentForeignKey: ceatlastzero2.cern.ch
GLUE2BenchmarkID: ceatlastzero2.cern.ch_specint2000
GLUE2BenchmarkComputingManagerForeignKey: ceatlastzero2.cern.ch_ComputingElement_Manager
dn: GLUE2BenchmarkID=ceatlastzero1.cern.ch_specint2000,GLUE2ResourceID=ceatlastzero1.cern.ch,GLUE2ServiceID=ceatlastzero1.cern.ch_ComputingElement,GLUE2GroupID=resource,GLUE2DomainID=CERN-PROD,GLUE2GroupID=grid,o=glue
GLUE2BenchmarkExecutionEnvironmentForeignKey: ceatlastzero1.cern.ch
GLUE2BenchmarkID: ceatlastzero1.cern.ch_specint2000
GLUE2BenchmarkComputingManagerForeignKey: ceatlastzero1.cern.ch_ComputingElement_Manager
```

**Comment by andresailer** [comment]
So we could just drop the `si00/250.` scaling factor?
I think the 60. is needed to go from the maxCPUTime in the queueDict, which is in minutes (!) to seconds

**Comment by fstagni** [comment]
Ah right sorry.
I would personally drop it but maybe @atsareg has something to say.

**Comment by atsareg** [comment]
The si00/250 scaling factor is attempting to transform cpu time in time units into HS'06 time units. So, if SI00 is not specified it can be replaced by just a factor 10 (conservative one core CPU power estimate in HS'06). In the code the corresponding constant can be explained is one-core CPU HS'06 power estimate. I would not be against of dropping the SI00 altogether and replace it by this factor of 10 but if it is defined why not to use it ? If HS-06 benchmark is defined, I think we can use it instead as this correction factor as it is. But we should be sure that this value is related to a single core of a CPU. We can introduce a reasonable range for checking the value validity like 5-20.

Are we sure that the maxCPUTime is always in minutes in Glue 2 as well ? Anyway if it is sometimes not, this would be a mess that should be reported and corrected by sites. May be we should introduce a reasonable range for this value also like 100-3000.

**Comment by andresailer** [comment]
In glue2 the maxCPUTime is supposed to be in seconds,
https://github.com/DIRACGrid/DIRAC/blob/d7aa596b6b8a2c6a1241655590fcaac544f444fc/Core/Utilities/Glue2.py#L107
 but not all publishers read the specification properly, so some of them are in minutes...
Which is why there is this beautiful piece of code:
https://github.com/DIRACGrid/DIRAC/blob/d7aa596b6b8a2c6a1241655590fcaac544f444fc/Core/Utilities/Glue2.py#L114-L116
Yes, sites should be contacted in these cases, but as long as glue1 is still there, and other people want to move away from Glue2 to something different altogether this seems like a fools errand

**Comment by andresailer** [comment]
If we want to keep the SI00 I will add a dummy entry to the Glue2 that returns 2500?

**Comment by atsareg** [comment]
Fine with me for SI00 2500

**Comment by atsareg** [comment]
Just comment it properly in the code

**Comment by andresailer** [comment]
Work around for GLUE2 added
