### ISSUE TITLE
User suspended not take into account in VOMS2CSAgent

### ISSUE THREAD

**Issue by closier** [DIRACGrid/DIRAC#3990]
When you suspend a User in the VO, it is not reflected in the VOMS2CSAgent, so th euser continue form the DIRAC point of view to be active.

I suspend one user but the log said;
2019-03-15 08:55:32 UTC Configuration/VOMS2CSAgent INFO: Performing VOMS sync for VO lhcb with credentials joel@lhcb_admin
2019-03-15 08:55:53 UTC Configuration/VOMS2CSAgent/VOMS2CSSynchronizer INFO: There are 796 user entries in VOMS for VO lhcb
2019-03-15 08:55:56 UTC Configuration/VOMS2CSAgent/VOMS2CSSynchronizer INFO: There are 794 registered users in DIRAC VO lhcb
2019-03-15 08:55:57 UTC Configuration/VOMS2CSAgent INFO: Run user results: new 0, modified 0, deleted 0, new/suspended 0
2019-03-15 08:55:57 UTC Configuration/VOMS2CSAgent INFO: No changes to the CS for VO lhcb recorded at this cycle

**Comment by fstagni** [comment]
@atsareg would you like to look into this?

**Comment by fstagni** [comment]
@atsareg @chaen @zmathe @andresailer  Please provide your inputs here.

**Comment by chaen** [comment]
Contrary to what I said during the meeting, the banning of the IP is done in the service reactor, not in the AuthManager https://github.com/DIRACGrid/DIRAC/blob/integration/Core/DISET/ServiceReactor.py#L185

Clearly, the banning of the user can be done in `AuthManager.authQuery`, but it needs to be done carefully, since we can have hosts doing requests on behalf of users. But anyway, I'd say this is the place to do it.

As for how we define them: either we set add a parameter to the user (by hand or from VOMS), or we have a special group. I'm in favour of the first option BUT for performance reason, I would build a set of banned user (refreshed at regular intervals) as an attribute of the AuthManager.

**Comment by atsareg** [comment]
I agree that user status validation should be done in the AuthManager. 
One important caveat: for multi-VO installations users in principle can belong to different VO's. Apparently, they can be suspended in one but not in the others. This should be taken into account. For example, the following structure in the CS can be made:

   Registry
   {
       Users
       {
           atsareg
           {
               DN = ...
               eMail = ...
               Status
               {
                   Active = CTA 
                   Suspended = lhcb, biomed
                   Banned = traffic_league
               } 
           }
       }
   }

AuthManager will have enough info (user VO membership for a particular operation) to take its decision.

**Comment by chaen** [comment]
Hum, do we really need so many status ? How about having just `Banned` ? Then the question would be how is this list updated. Clearly, if the user is suspended in VOMS, it should be added there. We should also be able to manually add someone. But if a user was banned from VOMS, and is not anymore, it will rquire manual intervention. I think it's fair though. 
And for `Active`, I'd say it's useless as well, since we could consider it the default

**Comment by atsareg** [comment]
I agree that we can have only one status Banned or Suspended, at least until we will feel the need for more statuses. However, the value should still be the least of VOs for which this status is actual. For other VOs by default the user is Active.

**Comment by fstagni** [comment]
Up... 
I think this can be treated with some priority.

**Comment by fstagni** [comment]
I think this can be closed.
