### ISSUE TITLE
Question: are multiple brokers needed in stomp ? 

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4468]
At the moment, the `StompMQConnector` keeps a dict of `{IP: Connection}`, with each connection pointing to one IP of an alias. Is that really needed ? I think the library is more intended for a active passive mode, where you connect to one IP only, and reconnect if needed.

**Comment by chaen** [comment]
@fstagni @hgiemza apparently you requested that feature, according to @wkrzemien old emails  (2016)

**Comment by wkrzemien** [comment]
It was adopted from this code: https://github.com/DIRACGrid/DIRAC/pull/3160/files

**Comment by hgiemza** [comment]
If I remember correctly the case was as follows: when you successfully connect to a broker and at some point the broker fails there is no automatic reconnect to the second IP (this mechanism only works at init). During the time of the break, even if the other side sends messages to the second broker because it is aware of the problem, all messages are lost from the perspective of our client as there is no active subscription at the second broker.

**Comment by chaen** [comment]
Well this is solved I understand with the `ReconnectionListener`. https://stomppy.readthedocs.io/en/latest/api.html#dealing-with-disconnects
Correct @wkrzemien ?

**Comment by wkrzemien** [comment]
@chaen Yes, 
@hgiemza  The question is if we can remove the broker code, which would make it much more straightforward. For a moment, it seems that the interplay between ReconnectionListener and broker code causes the  reconnection problem. If it is not needed I can remove it.

**Comment by chaen** [comment]
@wkrzemien thanks, I am doing it already

**Comment by fstagni** [comment]
I guess this one could be closed.

**Comment by chaen** [comment]
No not yet, I Started the work but never finished
