### ISSUE TITLE
Using  exactly two slashes at the start of an LFN triggers bug in DirectoryManager

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4578]
Example: (command with typo triggers bug)
dirac-dms-add-file //lz/user/daniela.bauer/test/dmslfnrep.1587389952.txt dmslfnrep.1587389952.txt UKI-LT2-IC-HEP-disk

DirectorySecurityManager must be enabled to trigger this bug.

Error in the file catalogue log:
 File "/opt/dirac/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryTreeBase.py", line 535, in getDirectoryPermissions
    result = self.getDirectoryPermissions(pDir, credDict)

Hot fix:
DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py
line 517:
-  if path == '/':
+ if path == '/' or path == '//':

Curiously it works fine with a triple slash at the start of the LFN.

We aren't quite sure how to fix this properly.

**Comment by chaen** [comment]
Just for info, in LHCb, using v7r0 and the `PolicyBasedSecurityManager`, there is no issue:
```
[chaen@lxplus701 chaen]$ dirac-dms-add-file //lhcb/user/c/chaen/hell.py hell.py  CERN-USER
Uploading hell.py as /lhcb/user/c/chaen/hell.py
Successfully uploaded hell.py to CERN-USER (1.0 seconds)
```

**Comment by chaen** [comment]
that seems to be the problem:

```
In [3]: os.path.dirname('//')
Out[3]: '//'
```
called here https://github.com/DIRACGrid/DIRAC/blob/rel-v6r22/DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py#L532

**Comment by chaen** [comment]
The reason why you see it and I don't is because the `DirectorySecurityManager` systematically calls the problematic piece of code:
https://github.com/DIRACGrid/DIRAC/blob/rel-v6r22/DataManagementSystem/DB/FileCatalogComponents/SecurityManager.py#L116
While in LHCb case, it's only a last resort:
https://github.com/DIRACGrid/DIRAC/blob/rel-v6r22/DataManagementSystem/DB/FileCatalogComponents/SecurityPolicies/VOMSPolicy.py#L229

So in theory it could happen to us as well.

Unfortunately, I do not see any real solution now, simply because we already had the discussion about where to sanitize the input and what to do with it about 13489545 times (+- 2). We never converged and always enter religious wars. 
So I find this extremely depressing to say, but your fix is probably one of the least bad at the moment :-/ 

Maybe something a tad more generic and that would avoid the propagation to the problem somewhere else would be to change this condition

https://github.com/DIRACGrid/DIRAC/blob/165711a2aa82e96cbb77e9e8eace0a91d2983295/DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py#L533-L534

to 
```
if not pDir or pDir == path:
  return S_ERROR('Illegal Path')
```

So this will blow to the user face, which is good.

**Comment by marianne013** [comment]
Hi Chris, looks fine to me. 
Daniela

**Comment by marianne013** [comment]
Actually, the error message should give the user a hint: 'Illegal LFN Path (double-slash in path?)'
