### ISSUE TITLE
Handling job status when pilot got killed

### ISSUE THREAD

**Issue by mschnepf** [DIRACGrid/DIRAC#5124]
Some resources that are used in an opportunistic way release their resources for priority jobs. At some of these resources, the pilot gets a kill signal to release the resources. In my opinion, the job should be rescheduled because this situation is caused by the system/resource and not by the job.
However, DIRAC set the job to status `Failed?  with minor status `Job stalled: pilot not running`.  As a result, the user has to reschedule the job. DIRAC already detects this case (see below) but handled it, in my opinion, not correct. Is it possible to change it, or is there another opinion?

As far as I understood it, DIRAC detects that the job is dead [(due to missing updates within the stall time)](https://github.com/DIRACGrid/DIRAC/blob/master/src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py#L115-L120).
Furthermore, the status of the [pilot is checked.](https://github.com/DIRACGrid/DIRAC/blob/master/src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py#L202-L235) If the pilot is dead, the job goes into the Status "Failed"  and the minor state `STALLED_PILOT_NOT_RUNNING = 'Job stalled: pilot not running'`

**Comment by fstagni** [comment]
Hi and thanks for the report/question. 

Your understanding is correct. What you are asking is basically to reschedule jobs that were run by pilots that have been killed by the batch system, instead of setting them to "Failed".
The reason why the jobs are set to "Failed" in the above case comes from the fact that we have no way to know the reason why the pilots are killed (the batch system does not communicate it). For the case of opportunistic resources and preemptive computing slots that you describe it would indeed make more sense to reschedule, but unfortunately this is a niche case. Most of the time (at least in our experience) the pilots are killed because they exceed the BS limits (e.g. CPU/wall time limits, or memory). Suppose that you reschedule a job that exceeds the memory limit: such job would end up being rescheduled n times and just wasting CPU time.

Now, your use case if real, so we could add an option to the StalledJobAgent to reschedule instead of failing jobs. That can maybe be Site-dependent?

**Comment by mschnepf** [comment]
Hi fstagni
 
Thank you for this information. Yes, it is not easy to see why the pilot was killed. I am only working with DIRAC for a short time, but is it possible that the watchdog process also ensures the limits and issues a correct message?

We are currently providing some resources which use preemption to a DIRAC instance.   
The idea of an option for rescheduling in the case of StalledJobAgent sounds good.

**Comment by fstagni** [comment]
The watchdog identifies when a job is not consuming CPU and thus set such job as "Stalled".
But, the watchdog can not know a priori what are the memory limits of the queue (and sometimes there are no such limits at all) -- and sometimes jobs are not run in any queue, and there's no batch system. 
The watchdog can know, under certain circumstances, the length of the queue, so in this case we try to not match jobs that most probably "won't fit".

I can code a simple fix for StalledJobAgent to take into account preemption on a site basis (I will do it in the next days), but be aware that for this case the agent might end up rescheduling jobs that should better be set to Failed.
