### ISSUE TITLE
[URGENT] Rucio MUST be an optional dependency

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5250]
Not only did we have to put horrible hacks in the code (https://github.com/DIRACGrid/DIRAC/issues/5193) but having Rucio as a dependency for everybody creates issues for everybody (including VO that has nothing to do with Rucio, random example: LHCb) 

Current situation is that we are totally unable to make an LHCbDIRAC release because our tests don't pass. And they do not pass because Rucio explicitly requires `stomp.py 6.1.1` (https://github.com/rucio/rucio/blob/master/requirements.txt#L28) which is broken (https://github.com/jasonrbriggs/stomp.py/issues/350#issuecomment-815302982)

So whatever the solution is, Rucio has to be made TOTALLY optional, and quickly.

**Comment by chaen** [comment]
@sfayer @marianne013 @martynia for opinions

**Comment by sfayer** [comment]
Hi,

As I understand it, this specific blocker issue is fixed: The server requirements were pulled in by mistake rather than the cut-down client requirements (stomp certainly isn't used by the client).

More generally, I agree that we don't want to be blocking any releases or causing any extra work for anyone, but it seems to me this situation is already rapidly improving. There is understanding from the rucio side that the client dependencies were excessive and they have already reduced these and are looking at relaxing the version pinning. There was a brief talk on this last week, if you're interested:
https://indico.cern.ch/event/1043884/contributions/4386000/attachments/2275330/3865218/RucioLightweightClient_20210528.pdf

My hope on this is that the difficulties are now over and there certainly seems to be an upstream consensus that these issues can and will be avoided in the future. Can we please see how it goes in the next couple of months before deciding on whether to split this all out into an extension?

Regards,
Simon

**Comment by chaen** [comment]
I agree with you that it goes in the good direction, but I still hate the fact that it will always be the same bunch of idiots that will be trying to find "why does the CI fails" to conclude on a DIRAC/Rucio interaction problem. Splitting things makes the problem clear.
 
But okay, we can wait for a bit to split under 2 conditions:
* right here and now, a responsible for that is named
* if that sort of issues (a VO blocked for weeks (!!!!) because of that bridge) arises again in a short/medium term feature, we split, with no further discussion. Sort of a "last chance" :-) 

> My hope on this is that the difficulties are now over

That, made my day though ! How much do you actually believe that sentence ? it's only getting started :rofl:

**Comment by bari12** [comment]
Hi all,

Apologies, I only saw that thread now. I don't know the DIRAC code too well, so what I am saying might not be easy/make much sense, but I would certainly recommend not to make Rucio a mandatory dependency but only pull it in for people actually using it. That it needs to be tested in the CI makes this a bit more complicated, but separating it in the CI how @chaen suggested at least quickly identifies the guilty ;-) and might unblock people not using Rucio.

As @sfayer mentioned, please use the `rucio-clients` package/containers. I would probably suggest to also somewhat pin/limit the version and semi-continuously update these, so you are not directly exposed to possible issues in the latest. 

For the clients: They will be Python 3.9 compatible (They already are, but it's excluded in the manifest) with the 1.26 release, currently in RC2, release probably this/next week. There are 6 mandatory dependencies in them https://github.com/rucio/rucio/blob/99b5095f566ba84c10410eda157a2d621df4d055/requirements.txt#L1 If some of them are an issue, we can discuss, the only strictly necessary are requests and urllib, others we can probably find a workaround.
Not using the Rucio clients, and going against the REST is of course also an option.

I am happy to be listed as the responsible and be blamed if things go wrong ;-) If it is an issue within Rucio/the packaging, we will fix it, if it is in between DIRAC/Rucio the least I can do is relaying the issue within the Rucio dev team, since there are several people (@cserf @sfayer Janusz ...) looking into DIRAC-Rucio.

Cheers,
Martin

**Comment by chaen** [comment]
Thanks for kicking in @bari12  
I seem to remember a Rucio slide where you had names of responsible for each area of Rucio (like Core, etc), and there was one such a box for DIRAC integration. Unfortunately, I can't find that slide anymore :-) 
To me, it would make sense that the same person step in here.

**Comment by bari12** [comment]
Yes, that would be @cserf ([component responsibles](https://rucio.cern.ch/documentation/component_leads)) but Cedric is on vacation at the moment and in general quite busy with other tasks. Until we have figured out if Cedric can continue to coordinate these efforts (From Rucio side), or if somebody else should continue, just contact me/list me in case of any issues. 😄

**Comment by fstagni** [comment]
Right now there's no issue, but could be re-open at any time.

**Comment by chaen** [comment]
`rucio-clients-1.29.0rc1` results in failing test.
So, can we finally make this dependency optional ? Or at least not take release candidates ?!

**Comment by marianne013** [comment]
Simon has already fixed it:
https://github.com/rucio/rucio/issues/5704
Now go back to changing some nappies, all of you.
