### ISSUE TITLE
parseCommandLine vs initialize

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#6019]
TL;DR;
=====

I'm lost as to what does what and what should I use.

Longer version
===========

I understand from https://github.com/DIRACGrid/DIRAC/pull/5713#issuecomment-1032924882  that if I write a simple dummy script, I just have to do

```python
from DIRAC import initialize
initialize()
```

and I am good to go. 
But I noticed that `initialize` does not load config files given as arguments (see below). So is there a bug ? Am I using it wrongly ? Where is the doc ? Where is the migration doc for the extensions ? 

Example
=======

This is `test.cfg`

```python
DIRAC
{
  Setup = toto
  test=Chris
}
```

With `parseComandLine`

```python
from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
from DIRAC import gConfig

print(gConfig.getValue('/DIRAC/test'))
```

```bash
python withParse.py --cfg test.cfg 
Chris
```

With `initialize`

```python
from DIRAC import initialize
initialize()
from DIRAC import gConfig

print(gConfig.getValue('/DIRAC/test'))
```

```bash
 python withInit.py --cfg test.cfg 
None
```

**Comment by chrisburr** [comment]
This is intentional as when using DIRAC as a library it shouldn't be looking at what's passed on the command line. Imagine the use case of ganga, arguments like `--cfg` and `-d` are for ganga's own use. (This is imaging they hadn't resorted to their RPC due to DIRAC not working like a library.)

`initialize` should probably have arguments to make common tasks easy (logging level? cfg files? set the proxy/certificate location?).

**Comment by chaen** [comment]
OK, I am happy with that answer.
But all that clearly needs documenting.

**Comment by TaykYoku** [comment]
As I known some documentation already exist:

RTD:
https://dirac.readthedocs.io/en/integration/DeveloperGuide/AddingNewComponents/DevelopingServices/index.html
Wiki:
https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-8.0#deprecated

Need to add something else?
