### ISSUE TITLE
GET requests to AuthHandler are not processed

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6245]
Now that https://github.com/DIRACGrid/DIRAC/pull/6128 has been merged the `TornadoREST` class no longer supports handling HTTP `GET` requests.

The only affected class is `AuthHandler` for handling OAuth logins so the only affected installation is https://lbcertifdiracoauth.cern.ch/

Ideally we should come up with a good plan with how to have "modern" HTTP REST services in DIRAC though the requirements/design should be discussed and prototyped extensively before implementing it properly.

Obviously it's not reasonable to wait that long for the release of 8.0.0 I think we should:

* [ ] Modify `AuthHandler` to look more like the WebAppDIRAC handler classes (i.e. using `web_` method prefixes) and do the bare minimum
* [ ] Add integration test coverage for `AuthHandler`
* [ ] Rename `TornadoREST` to `TornadoWeb` or something similar and remove support for using `SUPPORTED_METHODS` as the method prefixes (i.e. `get_`/`post_`/`put_`/`patch_`/`delete_`)

**Comment by atsareg** [comment]
We have to proceed with lots of tests of the OAuth related functionality which are now completely blocked by merging #6128. While this is solving the problem of extensions the other stuff is also very important. I think we have to add a quick fix proposed by Andrii which solves the extension problem without breaking the OAuth even despite it is deemed "fragile". Then a better solution can be still looked for. What is proposed is a lot of work for the OAuth machinery without a clear outcome and will delay the OAuth related tests indefintely, hardly acceptable.

**Comment by TaykYoku** [comment]
@chrisburr Thank you for creating this issue.

#6128 PR was merged ignoring my warning and without my approvement. The problem described here is expected and I described it in [comment](https://github.com/DIRACGrid/DIRAC/pull/6128#discussion_r889486911). 
I think that the most simple and reasonable solution is to cancel #6128 PR, this will remove restrictions on the use of `GET` methods and unlock work on the 8.0 release.
Next, there is the problem of "discovery of HTTPS methods from parent classes". I've proposed a solution with minimal code changes that doesn't hurt speed and doesn't create new problems. IMHO, if this solution is not acceptable, then it is necessary to offer a full-fledged better solution.

> The only affected class is AuthHandler for handling OAuth logins so the only affected installation is https://lbcertifdiracoauth.cern.ch/

It's hard for me to understand what was meant here, to be honest. At least the information is incorrect, because the prerelease is installed not only on **lbcertifdiracoauth.cern.ch**, but also on **dirac.egi.eu**, for example.
We had many discussions and agreements that led to the creation of the framework as it is now. And every time a prerelease is created on **lbcertifdiracoauth.cern.ch**, certification is conducted (this is not a full-fledged certification, because it is conducted only by me).

Also, I would like to point out that `TornadoREST` uses not only **DIRAC**, but also the **WebAppDIRAC** project, and it was planned to implement the already outdated **RESTDIRAC** in this way. In the DIRAC project, there is only `AuthHandler` that inherits `TornadoREST`, but only because it was decided to add a minimum of such handlers to the release. 

Personally, I am categorically against blocking the release again and every time returning to rework the framework that has already been reworked and agreed upon several times. We have already had many large discussions like [this](https://codimd.web.cern.ch/2ctS6OH5QZiMJqJLXaMivw?view), where I repeatedly spoke about the need for a REST interface, its use, about the threats of delaying the implementation of the main feature (OAuth authorization, as the first stage of token integration), which we agreed to add in **v7r2**, if I remember correctly.

I propose to break down a very complex problem into simpler ones, which will help to quickly deal with it:

* [ ]  review/apply https://github.com/DIRACGrid/DIRAC/pull/6249. That's it, at this stage the problem disappears.
* [ ]  Add integration test coverage for `TornadoREST`
* [ ]  renew long-started discussions regarding "good plan with how to have "modern" HTTP REST services in DIRAC"

**Comment by chrisburr** [comment]
> At least the information is incorrect, because the prerelease is installed not only on lbcertifdiracoauth.cern.ch, but also on dirac.egi.eu, for example.

Apologies I was unaware of this. From the BiLD meeting reports I thought the EGI installation was still running v7r3 with Python 2?

> What is proposed is a lot of work for the OAuth machinery without a clear outcome and will delay the OAuth related tests indefintely, hardly acceptable.

The fact the CI still passes despite such an apparently critial feature being broken is a serious issue that should be addressed. Major new functionality should have good test coverage and https://github.com/DIRACGrid/DIRAC/pull/6128 would never have been merged if the CI was failing as a result.

> Also, I would like to point out that TornadoREST uses not only DIRAC, but also the WebAppDIRAC project, and it was planned to implement the already outdated RESTDIRAC in this way.

I'm aware, however only I think `WebAppDIRAC` only uses the `web_` prefix and doesn't use the `get_`/`delete_`/... prefixes which I think are problematic?

**Comment by atsareg** [comment]
If I understand correctly, #6128 prevents classes derived from TornadoREST to implement methods that potentially can conflict with methods provided by tornado. The latter provides some methods with the `get_` prefix but with some well defined method name. So, if TornadoREST derived classes do not implement methods with exactly the same full name as the tornado one, then there is no conflict possible. I am pretty sure that this is a no problem. If even by chance there is a coincidence, it will be revealed while the testing/certification process. If some future tornado version will add some more methods of this kind, this will be discovered and fixed once while testing. So, I do not think that even #6245 is necessary although this will prevent such potential conflicts it is an overkill check for never happening things. It is sufficient to just remove the exception for `get_` methods in #6128. I think this will be enough minimum necessary for the 8.0 release which is both extension and OAuth compatible. Even more so with the additional checks proposed in #6245 although I think there are redundant.    
Adding CI tests coverage is of course necessary.
