### ISSUE TITLE
self.ceParameters returns only values from CEDefaults

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/DIRAC#6404]
Hi,

While working on the AREXComputingElement, I am trying to use self.ceParameters to return the defined parameters from the configuration for the given CE. However, this returns only the values from CEDefaults.

It looks to me like this feature is not really used during the initialization phase by any other CE and so I am hitting this issue. Could someone point out to me what other initialisation I need to call for the ceParameters to be properly filled.

Thanks and Cheers,
Raja.

**Comment by rajanandakumar** [comment]
Resolution of this wiill help me with the issues

https://github.com/DIRACGrid/DIRAC/issues/6260

https://github.com/DIRACGrid/DIRAC/pull/5542

Cheers,
Raja.

**Comment by sfayer** [comment]
Hi Raja,

The initialisation of ceParameters is normally done in two steps:
The defaults are filled out by the ComputingElement.initializeParameters which is called from the base constructor:
https://github.com/DIRACGrid/DIRAC/blob/9dc204e1d8feb4c49be68c91f40176bbfc4b9fdf/src/DIRAC/Resources/Computing/ComputingElement.py#L84

The rest of the parameters (including the CE & queue specific details) are filled out a little bit later on when ComputingElement.setParameters is called (normally just after the constructor, if the CE is instantiated in the standard way):
https://github.com/DIRACGrid/DIRAC/blob/073655c5ab05ae8d270295b5ca20cc297f5bbbba/src/DIRAC/Resources/Computing/ComputingElementFactory.py#L50-L55

It's probably best to either override/extend setParameters (still calling the base function first) and do stuff there rather than `__init__`, or later in functions like submitJob: Pretty much anywhere other than `__init__` should work!

Regards,
Simon

**Comment by rajanandakumar** [comment]
Hi Simon,

Thanks for this. So, it works as long the initialisation is not done at initialisation time. It needs a slightly different philosophy but I can work with this.

Cheers,
Raja.
