### ISSUE TITLE
wholeNode parameter is still needed in Condor.py?

### ISSUE THREAD

**Issue by zhangxiaomei** [DIRACGrid/DIRAC#6598]
In the Resources/Computing/BatchSystems/Condor.py, "wholeNode" is always set to be "True" since the parameter "WholeNode" is absent, which makes condor job submission failed with the tag"CAN_RUN_WHOLE_MACHINE" in the requirement.
From SSHComputingElement.py, no "WholeNode" option is to be passed to the executable execute_batch (Condor.py is one part of it).
Do we still need the "wholeNode"  here?

**Comment by zhangxiaomei** [comment]
In the siteDirector log,  it did have "WholeNode=False" as input of execute_batch.
I did a test directly with the execute_batch command by hand. With an input "WholeNode", I found that to run with python2, the input "WholeNode=False" makes the following code running into "if wholeNode" instead of "else"
    if wholeNode:
      requirements = '+RequiresWholeMachine=True\n Requirements = ( CAN_RUN_WHOLE_MACHINE ) && ( OpSys == "LINUX" )'
    else:
      requirements = 'Requirements = OpSys == "LINUX"'

To fix this, the following change is needed:
   wholeNode = kwargs.get('WholeNode')   ->  wholeNode = eval(kwargs.get('WholeNode'))

**Comment by aldbr** [comment]
> In the siteDirector log, it did have "WholeNode=False" as input of execute_batch.

Could you check whether you have `WholeNode=False` defined somewhere in your CS? I suspect it is defined, and because of that, `False` is passed as a string instead of a boolean, and `Condor.py` does not check the type of the value.
`wholeNode` is defined as `"False"` instead of `False`, and thus, `if wholeNode:` is interpreted as true.

If such is the case, as a temporary solution, I suggest you to remove the option from your CS: `WholeNode=False`. The default value is `False`.

We could fix it by converting the string into a boolean but I wonder whether this `RequiresWholeMachine` option is still available.
I found some old examples but cannot find it in the official documentation.

Seems like you introduced this option in the code in 2017: https://github.com/DIRACGrid/DIRAC/commit/0e1011a16aedeb6e99772583fa6ed45c0d6e4e23
Are you still using it? According to your title, you don't use it anymore. If this is the case, then I guess that we can just drop this option.

**Comment by zhangxiaomei** [comment]
Thank you for reminding me. I nearly forgot it.  We are not using the WholeNode parameter any more.  If keep it, wholeNode="False" is a little bit confusing and to allow wholeNode=False is better.  It is easy to run into a problem since other options use False.

On the other hand,  the method of "'+RequiresWholeMachine=True\n Requirements = ( CAN_RUN_WHOLE_MACHINE ) " is out-of-date for current Condor version. Also other batch systems don't need that. I think we can drop it for Condor.

**Comment by aldbr** [comment]
You are using DIRAC v7r3, aren't you?
I am going to make a PR to drop the option since it seems deprecated + you don't use it + I don't think anyone is using it.
@fstagni we should probably ask this at the next bild meeting before removing the option, what do you think?

**Comment by fstagni** [comment]
Make the PR and then we can merge it after the next BiLD.

**Comment by zhangxiaomei** [comment]
> You are using DIRAC v7r3, aren't you? I am going to make a PR to drop the option since it seems deprecated + you don't use it + I don't think anyone is using it. @fstagni we should probably ask this at the next bild meeting before removing the option, what do you think?

Yes. I am using DIRAC v7r3. No problem.
