### ISSUE TITLE
CA certificates for submitting htcondor with tokens

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6893]
In order to submit to many htcondor CEs the path the CAs has to be overriden. With X509 auth this was done with the `X509_CERT_DIR` environment variables however this seems to be ignored when submitting with tokens.

From checking it appears the only way to change the CAs is to set `AUTH_SSL_CLIENT_CADIR` in the htcondor config. This is not practical to do in DIRACOS so we need another solution.

@atsareg should contact the htcondor authors to see if there is a way to set this with an environment variable of if one can be added.

If this isn't possible the only solution will be to write a temporary file and set `CONDOR_CONFIG`.

**Comment by atsareg** [comment]
The HTCondorCE developers confirmed that setting the _CONDOR_AUTH_SSL_CLIENT_CADIR env variable should be taken into account as expected. Although some past tests failed to do that, now it works indeed. I have set it up in the /opt/dirac/bashrc on lbcertifdirac70 and dropped from the condor_config and it works. So, the issue is closed.

**Comment by chrisburr** [comment]
Shouldn't this by handled by the agent rather than requiring a specific variable to be set by admins?

**Comment by atsareg** [comment]
Can be done in the agent indeed

**Comment by chaen** [comment]
Please, please, please. Stop editing files on lbcertifdirac70. They are managed by puppet. Then things don't work anymore, and we wonder why, and start blaming in the wrong direction.
