### ISSUE TITLE
MultiVOMetaData: prevent creating of metadata tags involving ___[vo name]

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#7718]
This is a reserved character sequence and users should not be allowed to create metadata ending in ___[vo name].

**Comment by marianne013** [comment]
@martynia Before I forget.

**Comment by martynia** [comment]
For  a multi-VO catalog, the "reserved" characters are not an issue. The VO extension will always be there, and it will be stripped off before returning it to a user.  The problem was in searching, where an extra VO suffix was added to the name which was searched for (a DB record was not modified). Fixed by #7708.

**Comment by marianne013** [comment]
I think we agreed this was done.
