### ISSUE TITLE
Database optimizations

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#7721]
Is there any way to make these queries a bit more robust ? It doesn't matter if they take a while, it's more important that they work eventually.
```
(base) XPS:~/temp/dfc_clean/lancaster $ dirac-dms-find-lfns Path=/[t2k.org](http://t2k.org/) --SE=UKI-NORTHGRID-LANCS-HEP-disk > t2k_lancs.list
(base) XPS:~/temp/dfc_clean/lancaster $ cat t2k_lancs.list
Can not access File Catalog: FileCatalog error ( 1604 : Failed to perform findFilesByMetadata from any catalog)
```

**Comment by fstagni** [comment]
The first (and very generic) answer regarding database optimizations is about running a defragmentation (https://mariadb.com/kb/en/optimize-table/). Note that:
- this requires a downtime
- it will almost certainly improve the DB used space
- it won't necessarily improve matters on the query performance level
we defragmented all LHCB databases around 1 year ago and recovered a substantial amount of space. We did not monitor performances.

In order to properly know what is going on, and to know if the query can be improved, I would suggest an `ANALYZE`: https://mariadb.com/kb/en/analyze-statement/ of the query.

**Comment by fstagni** [comment]
And additional info: error code 1604 is generic File Catalog Error so not much can be inferred.

In any case: I suspect the "DIRAC-Way" of doing the query above (and treating its results) would be through the Transformation System.

**Comment by chaen** [comment]
It did improve the performances quite a bit on some DB.

Regarding the specific query you asked for, I checked while we were sitting together in Lyon, but I don't think it can be made better with the current directory table implementation.

**Comment by marianne013** [comment]
I guess we'll give up for now.
