### ISSUE TITLE
Pilot not matching jobs

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#778]
When a pilot is not matching a job, there may be several reasons:
1. No job corresponding to the capabilities: not much to do ;-)
2. Too many jobs running of the available type(s): ibid
3. There are waiting jobs, but the matching delay was not long enough

In this last case, I would suggest that the pilot "loses" a bit of time in waiting in an exponential way, e.g. 10, 20, 40, 80,160 seconds. The worse is to be inefficient for a couple of minutes, but in most cases (if scheduling is not wild) it should help.

On the same vein: when a job fails, the pilot gives up filling mode. There is no compelling reason for this and I would suggest to make this a configuration parameter that can be turned off (in LHCb)

**Comment by fstagni** [comment]
Is this issue still a valid one?

**Comment by phicharp** [comment]
As we alluded to recently, I think we should, at least for LHCb, use a completely different strategy for pilot submission.
My proposal would be to use the same strategy used by vcycle and vac i.e. to throttle pilot submission as soon as pilots report they have not matched any job. This would allow a full decoupling (which anyway is kind of fake) between the site directors and the task queues, since we don't submit a pilot on behalf of a job. 
This submission would be much more elegant and avoid any flooding of sites with pilots not matching. Anyway the initial point was a red herring since we heard nothing about it for 3 years!
Is the job limit and the matching delay a show-stopper for this kind of strategy? Probably it requires more thought...

**Comment by atsareg** [comment]
I think there are many ways in how the pilot submission can be improved. For LHCb, explicit throttling of the pilot submission if no matching jobs found can be a kind of coping with the case of job limits and matching delays. For others, who do not use these instruments, throttling does not make sense since piltos will not be sent if no more jobs in the queues. Decoupling of task queues and site directors - this is how we worked in the very first days of DIRAC by just maintaining a certain level of waiting pilots at the sites. The problem with pilot throttling is who and how will decide that the throttling should be stopped ?

**Comment by fstagni** [comment]
Duplicate task.
