### ISSUE TITLE
Matcher logging is incorrect

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7884]
In https://github.com/DIRACGrid/DIRAC/pull/4978 subloggers were added for the matching process however the same DB instance is used for all matching requests meaning the logs are meaningless when multiple matching requests are being processed:

https://github.com/DIRACGrid/DIRAC/blob/df964500f8fe5d73aaf2e59fdc5532958dc41e7b/src/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py#L60-L68

**Comment by fstagni** [comment]
I don't want to move to 
```python
matcher = Matcher( 
     opsHelper=opsHelper, 
     pilotRef=pilotRef, 
 ) 
 result = matcher.selectJob(resourceDescription, credDict) 
 ```
 
 so maybe I simply remove these lines:
 
 https://github.com/DIRACGrid/DIRAC/blob/df964500f8fe5d73aaf2e59fdc5532958dc41e7b/src/DIRAC/WorkloadManagementSystem/Client/Matcher.py#L54-L57

**Comment by chrisburr** [comment]
I think the logging is valuable. I haven't thought it through but could you make log a contextvar?

**Comment by aldbr** [comment]
First I checked the [logging cookbook](https://docs.python.org/3/howto/logging-cookbook.html), they have a [specific section about contextvars](https://docs.python.org/3/howto/logging-cookbook.html#use-of-contextvars). The approach looks correct but not really convenient. The idea would have been to pass the pilot reference within a `contextvar` but then we would have needed a specific `Filter` and to add it in the `BaseFormatter`.
 
A simpler approach is to pass the name of the logger or the logger itself in the `contextvar`. It is simpler, though not that easy to follow since it needs specific logic within the DB classes. Here is my proposal: https://github.com/DIRACGrid/DIRAC/pull/7924
