### ISSUE TITLE
Token-only submission to ARC-CE with HTCondor batch fails

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#7908]
Hi,

While pre-prod testing the latest version of v8 (8.0.59) we've found that a number of ARC-CEs failed to accept the pilot job submission. What I think is happening is that this patch means the proxy isn't included at the CE level at all: 
5d1ec5923f032c205c122dc2e3c5645883139932
Most of our sites, at least in the UK, have "ENV/PROXY" RTE enabled by default and this requires a proxy is present, so we ultimately see this in the Pilot LoggingInfo:
```
cat: /var/spool/arc/jobstatus/job.<arc job ID>.proxy: No such file or directory
...
job *NOT* submitted successfully!
got error code from condor_submit: 1 !
Output is:
Submitting job(s)Error output is:
ERROR: unable to read proxy file
```
This seems to specifically affect sites with HTCondor batch system behind the CE, although we haven't tested a very wide range of sites.

I'm not sure how we can get this fully fixed in a sensible manner: Perhaps we can roll back this change for now? Or is there some other way we can approach this?

[Bonus question: Does CE-level accounting work correctly if the proxy isn't present? I thought APEL still required VOMS role information]

Regards,
Simon

Tagging @marianne013

**Comment by aldbr** [comment]
> Most of our sites, at least in the UK, have "ENV/PROXY" RTE enabled by default and this requires a proxy is present

Oh I see now, I did some tests with the help of the admins at UKI-SOUTHGRID-RALPP, they patched something for this `ENV/PROXY` problem but I don't know what they did exactly, and whether it's a hack.

>  Does CE-level accounting work correctly if the proxy isn't present? I thought APEL still required VOMS role information

I also did some tests with admins at PIC and they reported a problem with the accounting, so they decided to wait for ARC v7.

For all these reasons, in LHCb for now, we don't use tokens with ARC CEs (only with a very limited number of instances) and wait for the deployment of ARC v7.

> I'm not sure how we can get this fully fixed in a sensible manner: Perhaps we can roll back this change for now? Or is there some other way we can approach this?

Good question, we could roll back indeed, but then what would be the point of using both tokens and proxies? (tokens would not even be used in the authentication process IIUC).

**Comment by marianne013** [comment]
Our tests fail at UKI-SOUTHGRID-RALPP in 8.0.59. Did they by any chance only implement this for LHCb ?

**Comment by aldbr** [comment]
Good question :man_shrugging: 

Here was the [response](https://ggus.eu/index.php?mode=ticket_info&ticket_id=168549) of the admin: 
> I don't think it's related to that, I think it's because we've got a default Arc Runtime Environment of ENV/PROXY which, it appears, tries to set up proxies even when there's no proxy present.
> I've got a patch from Glasgow which is supposed to fix this, so I've applied it [...]

**Comment by aldbr** [comment]
To sum up, before https://github.com/DIRACGrid/DIRAC/commit/5d1ec5923f032c205c122dc2e3c5645883139932, the token logic was broken: tokens were not involved in the submission process (because of a bug in ARC v6). This was not visible on our side, we randomly discovered that because of another issue when we discussed with UKI-SOUTHGRID-RALPP.

IIUC, you moved to tokens everywhere by adding `Tag = Token`, right?
But because tokens were not used before `v8.0.54` in ARC instances, everything seemed fine. Now that tokens are used and that some sites need to apply a patch, you start seeing some issues.

I see 2 possible solutions to the problem:
- you remove `Tag = Token` in your CS when a given ARC instance does not support tokens (because sites need to patch the `ENV/PROXY` RTE first, or wait for v7).
- we roll back the change for `v8.0`, in this case we remove token support on ARC instances.

I would have a preference for the first solution if it's not too much work on your side, since some instances can already work with tokens and `v8.0` was supposed to come up with token support (for computing resources).

What is your opinion?

**Comment by marianne013** [comment]
@aldbr But the tokens *do* get used somewhere - do you remember the email thread  (Oct10), because we had an odd type of certificate for the IAM server and the submission to ARC was failing ? I can't remember which version we were testing, but Oct 10 must have been 8.0.53. 
We do not want to go back from tokens, I'm surprised LHCb is letting this slide. 
Any chance of making "IncludeProxyAsWellForArc" an option somewhere ?

**Comment by aldbr** [comment]
But was the error related to tokens in the end? Which version of Dirac did you use at this moment?

I am a bit surprised because you are saying that you get this error in the latest release `v8.0.59`, but the last modification of the `AREXCE` was included on October 10th in `v8.0.54`. Have you tested the versions between `v8.0.53` and `v8.0.59`?

**Comment by marianne013** [comment]
According to my notes (history | grep "checkout") we tried 8.0.54 and 8.0.56.I don't remember if we ever got to the ARC though, there were other problems. I tried to quickly backtrack to 8.0.56, but of course it doesn't work out of the box due to the changes to tokenmanager.

**Comment by aldbr** [comment]
> Any chance of making "IncludeProxyAsWellForArc" an option somewhere ?

I don't think it makes sense:
- before `v8.0.54`: proxy & token were added to the request -> only the proxy was used by ARC, the token was ignored
- after `v8.0.54`: token is added to the request -> token used by ARC if patched (hacked) correctly

From what we are seeing, the hack that was put in place on many ARC instances was removed when site admins updated their instances:

> Try again, the new ArcCE version had reversed the Hack.
